kind: Component
spec:
  type: Lambda
  lifecycle: prod
  owner: Field_Engineering
  system: Platform_Demo
  dependsOn:
    - component:boutique-adservice
    - component:boutique-checkoutservice
    - component:boutique-currencyservice
    - component:boutique-emailservice
    - component:boutique-loadgenerator
    - component:boutique-paymentservice
    - component:boutique-productcatalogservice
  providesApis:
    - petstore
    - starwars-graphql
apiVersion: backstage.io/v1alpha1
metadata:
  name: Lambda-API
  description: My New Lambda
  tags: 
    - python
  annotations:
    harness.io/cd-serviceId: Python_AWS_Lambda
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: chrisjws-harness/idp-example
